# Generated by Django 4.2 on 2025-06-27 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("location", models.CharField(max_length=255)),
                ("manager_name", models.CharField(max_length=255)),
                ("clinic_code", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="userroleassociation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userroleassociation",
            name="role",
        ),
        migrations.RemoveField(
            model_name="userroleassociation",
            name="user",
        ),
        migrations.RemoveField(
            model_name="user",
            name="uuid",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("viewer", "Viewer"),
                    ("civicadmin", "CivicAdmin"),
                ],
                default="viewer",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Role",
        ),
        migrations.DeleteModel(
            name="UserRoleAssociation",
        ),
        migrations.AddField(
            model_name="user",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="iam.clinic",
            ),
        ),
    ]
